/**
 * `pnpm registry` — find every content/<conference>/<session>/bundle.json,
 * validate it, and write src/generated/registry.ts with static imports so the
 * app bundles its content (no file reads at request time). Run before build.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { EmbeddingsSchema, checkEmbeddings, parseBundle } from '../src/lib/bundle.ts';
import { EMBEDDING_DIMENSIONS, embeddingModelId } from '../src/lib/models.ts';

const root = new URL('..', import.meta.url).pathname;
const contentDir = join(root, 'content');
const out = join(root, 'src/generated/registry.ts');

const entries: { collection: string; dir: string; embeddings: boolean }[] = [];
for (const conference of readdirSync(contentDir).sort()) {
  const confDir = join(contentDir, conference);
  if (conference.startsWith('.') || !existsSync(confDir)) continue;
  for (const session of readdirSync(confDir).sort()) {
    const bundlePath = join(confDir, session, 'bundle.json');
    if (!existsSync(bundlePath)) continue;
    const bundle = parseBundle(JSON.parse(readFileSync(bundlePath, 'utf8')));
    const collection = `${conference}/${session}`;
    if (bundle.collection !== collection) {
      throw new Error(`${bundlePath}: bundle.collection is ${bundle.collection}, directory says ${collection}`);
    }
    const embPath = join(confDir, session, 'embeddings.json');
    const embeddings = existsSync(embPath);
    if (embeddings) {
      const emb = EmbeddingsSchema.parse(JSON.parse(readFileSync(embPath, 'utf8')));
      checkEmbeddings(bundle, emb, { model: embeddingModelId(), dimensions: EMBEDDING_DIMENSIONS });
    }
    entries.push({ collection, dir: `${conference}/${session}`, embeddings });
  }
}

const lines = [
  '// Generated by `pnpm registry` from content/*/*/bundle.json. Do not edit.',
  '',
];
entries.forEach((e, i) => {
  lines.push(`import bundle${i} from '../../content/${e.dir}/bundle.json';`);
  if (e.embeddings) lines.push(`import embeddings${i} from '../../content/${e.dir}/embeddings.json';`);
});
lines.push('', 'export const RAW_COLLECTIONS: { bundle: unknown; embeddings: unknown }[] = [');
entries.forEach((e, i) => {
  lines.push(`  { bundle: bundle${i}, embeddings: ${e.embeddings ? `embeddings${i}` : 'null'} },`);
});
lines.push('];', '');
writeFileSync(out, lines.join('\n'));
console.log(`registry: ${entries.length} collection(s): ${entries.map((e) => e.collection).join(', ')}`);
